// src/Components/Helpers/GoogleMap.vue
<!-- logic code -->
<script>
// you can get your own key at https://developers.google.com/maps/documentation/embed/
var browserKey = 'AIzaSyCqJHFVQI304o7geq7hfNigWd4XCapJl94'

export default {
  // a slightly more advanced example of how to use props that includes type validation (you'll get an error if you try to pass in something that isn't a String), and also provides a default value if you forget to supply a value.
  props: {
    place: {
      type: String,
      default: '26 Broadway, New York, NY'
    }
  },
  computed: {
    // this is a computed property that replaces every space charater in the place property with a '+' character.
    // e.g. "26 Broadway, New York, NY" becomes "26+Broadway,+New+York,+NY"
    placeConverted: function() {
      return this.place.replace(/\s/g, '+')
    },
    // this is a computed property that uses our key, and placeConverted property to generate the url in the format that Google Maps Embed API needs.
    url: function() {
      return "https://www.google.com/maps/embed/v1/place?key="+browserKey+"&q="+this.placeConverted
    }
  }
}
</script>

<!-- template code -->
<template>
  <iframe
  frameborder="0"
  v-bind:src=url
  allowfullscreen></iframe>
</template>

<!-- style code -->
<style scoped>
iframe {
  border: 0;
  width: 100%;
}
</style>

// src/Components/Helpers/GoogleMap.jsx
import React from 'react'
import css from './GoogleMap.css'

// you can get your own key at https://developers.google.com/maps/documentation/embed/
var browserKey = 'AIzaSyCqJHFVQI304o7geq7hfNigWd4XCapJl94'

export default class GoogleMap extends React.Component {

  getUrl() {
    var placeQueryString = this.props.address.replace(/\s/g, '+')
    return "https://www.google.com/maps/embed/v1/place?key="+browserKey+"&q="+placeQueryString
  }

  render() {
    return  <iframe
              frameBorder="0"
              src={this.getUrl()}
              allowFullScreen></iframe>
  }
}


// a slightly more advanced example of how to use props that includes type validation (you'll get an error if you try to pass in something that isn't a String), and also provides a default value if you forget to supply a value.
GoogleMap.propTypes = {
	address: React.PropTypes.string.isRequired
};

GoogleMap.defaultProps = {
  address: "26 Broadway, New York, NY"
};
